format = """
[░▒▓](#cc6379)\
[  ](bg:#cc6379 fg:#090c0c)\
[](bg:#39171e fg:#cc6379)\
$directory\
[](fg:#39171e bg:#394260)\
$git_branch\
$git_status\
$git_metrics\
[](fg:#394260 bg:#212736)\
$python\
$nodejs\
$rust\
$golang\
[ ](fg:#212736 bg:#1d2230)\
$time\
[](fg:#1d2230)\
\n$character"""

[directory]
style = "fg:#5ee0e3 bg:#39171e"
format = "[ ﱮ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[username]
show_always = true
style_user = "bg:#9A348E"
style_root = "bg:#9A348E"
format = '[$user ]($style)'
disabled = false

[git_branch]
symbol = " "
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#5ee0e3 bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'

[git_metrics]
format = "([+$added]($added_style))[]($added_style)"
added_style = "fg:#1C3A5E bg:#FCF392"
deleted_style = "fg:bright-red bg:235"
disabled = false

[python]
pyenv_version_name = true
pyenv_prefix = "pyenv"
python_binary = ['python', 'python3', 'python2']
detect_extensions = ['py']
detect_files = ['.python-version', 'Pipfile', '__init__.py', 'pyproject.toml', 'requirements.txt', 'setup.py', 'tox.ini']

[nodejs]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[rust]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[golang]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[  $time ](fg:#a0a9cb bg:#1d2230)]($style)'
